[package]
name = "aes_encryptdata"
version = "0.1.0"
edition = "2021"
authors = ["<rickporto.sec@gmail.com> <discord: @rickporto>"]

[dependencies]
openssl = "0.10"
rand = "0.8"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1 
panic = "abort"
incremental = false
debug = false
